
name: Build

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 0 1,11,21 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate hosts
        run: bash ./generate_hosts.sh

      - name: Upload hosts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          curl -Lo upload.sh https://github.com/probonopd/uploadtool/raw/master/upload.sh
          bash upload.sh hosts hosts-no-localhost
